apiVersion: apps/v1
kind: Deployment
metadata:
  name: skillsprint-learner-service-app
  labels:
    app: skillsprint-learner-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : skillsprint-learner-service-app
  template:
    metadata:
      labels:
        app: skillsprint-learner-service-app
    spec:
      containers:
      - name: skillsprint-learner-service-app
        image: isurux98/skillsprint-learner-service:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8075

---

kind: Service
apiVersion: v1
metadata:
  name:  skillsprint-learner-service-svc
spec:
  selector:
    app:  skillsprint-learner-service-app
  ports:
  - port:  80
    targetPort:  8075