spring:
  application:
    name: SERVICE-REGISTRY

server:
  port: 8761

#eureka:
#  instance:
#    hostname: "${HOSTNAME}.eureka"
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
