spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path= /api/v1/users/**
          filters:
            - AuthenticationFilter
        - id: course-service
          uri: lb://COURSE-SERVICE
          predicates:
            - Path= /api/v1/course-enrollment/**
          filters:
            - AuthenticationFilter
server:
  port: 8765
token:
  secret:
    key: hehe
  expirationms: 36000000
