spring:
  application:
    name: COURSE-SERVICE

  data:
    mongodb:
      uri: mongodb+srv://root:1234@cluster0.9dttrix.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: courseDB

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 8078

eureka:
  instance:
    prefer-ip-address: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka

#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
