spring:
  application:
    name: USER-SERVICE
  data:
    mongodb:
      uri: mongodb://user:1234@ac-yyparqg-shard-00-00.4emtz3f.mongodb.net:27017,ac-yyparqg-shard-00-01.4emtz3f.mongodb.net:27017,ac-yyparqg-shard-00-02.4emtz3f.mongodb.net:27017/skilldb?replicaSet=atlas-4x1yu3-shard-0&ssl=true&authSource=admin&retryWrites=true&w=majority&appName=Cluster0
token:
  secret:
    key: hehe
  expirationms: 36000000

server:
  port: 8077

#eureka:
#  instance:
#    prefer-ip-address: true
#    hostname: eureka-0
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    service-url:
#      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://user-service:8761/eureka/
  instance:
    prefer-ip-address: true