name: Deploy User  to EC2

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t rpyasiru/user-service:latest .
          docker push rpyasiru/user-service:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull rpyasiru/user-service:latest
            docker stop user-service || true
            docker rm user-service || true
            docker run -d \
              --name user-service \
              -p 8081:8081 \
              --network app-network \
              -e MONGO_URI="${{ secrets.MONGO_URI }}" \
              -e EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/ \
              -e TOKEN_SECRET_KEY=hehe \
              -e TOKEN_EXPIRATIONMS=36000000 \
              -e SPRING_PROFILES_ACTIVE=docker \
              rpyasiru/user-service:latest
