spring:
  application:
    name: content-service

  mongodb:
    uri: mongodb+srv://root:1234@cluster0.9dttrix.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    database: quizDB

server:
  port: 8087



